### ISSUE TITLE
add ansible task to run composer install on provision

### ISSUE THREAD

**Issue by allan-simon** [we-bridge/vagrant-ansible-symfony#5]
so that when someone vagrant up the machine, it is already development ready.

**Comment by cbrunnkvist** [comment]
Uh this probably got solved already by the new include-file that calls `symfony install` rather than `composer create-project ....`

**Comment by allan-simon** [comment]
ok let's close that then.

**Comment by allan-simon** [comment]
ok let's close that then.

**Comment by allan-simon** [comment]
ok let's close that then.

**Comment by allan-simon** [comment]
no actually it needs to be done, because symfony install ,  is only launched once , and when you have a colleague who clone/vagrant up your project, symfony install will not run, so that he needs composer install

or anytime the composer.lock is udpated

**Comment by cbrunnkvist** [comment]
Good point! And I suspect that you have noticed how symfony installer does NOT leave a composer executable anywhere after it finishes installation (sucks when "manually" demoing how to manually download the symfony installer "in order to avoid having to go via composer"...only realize that you cannot even fix the broken-by-install composer.lock file without, yes, go download the composer installer).

**Comment by allan-simon** [comment]
for which you have open an issue on symfony/symfony ? :) (honest question, if you didn't , I will)

**Comment by cbrunnkvist** [comment]
if you want, you do :)

I'm closing this ticket for now

**Comment by allan-simon** [comment]
no problem, i did here https://github.com/symfony/symfony-installer/issues/171  if you want to follow it.
